export const DEFAULT_ADMIN_SUBSCRIPTION_PLANS = [
  {
    code: "STARTER_ADMIN",
    name: "Starter Admin",
    description: "Best for 1 restaurant early-stage business",
    monthlyPrice: 1499,
    yearlyPrice: 14999,
    yearlyDiscountPercent: 17,
    offers: {
      monthly: {
        enabled: false,
        label: "",
        discountedPrice: 0,
        discountPercent: 0,
        durationMonths: 1,
      },
      yearly: {
        enabled: true,
        label: "Save on yearly billing",
        discountedPrice: 14999,
        discountPercent: 17,
        durationMonths: 12,
      },
    },
    maxRestaurants: 1,
    maxStaff: 10,
    extraRestaurantMonthlyPrice: 0,
    trialDays: 7,
    displayFeatures: [
      "1 Restaurant",
      "Up to 10 Staff",
      "POS / Orders / Billing",
      "Inventory Management",
      "Vendor Ordering",
      "Simple Analytics",
      "Email / Chat Support",
    ],
    features: {
      inventoryManagement: true,
      vendorOrdering: true,
      vendorSettlement: false,
      reportsAnalytics: "simple",
      exportEnabled: false,
      multiRestaurantDashboard: false,
      customSettlementCycles: false,
      auditLogs: false,
      prioritySupport: "email_chat",
      apiIntegrationReady: false,
    },
    isPopular: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    code: "GROWTH_ADMIN",
    name: "Growth Admin",
    description: "Best for growing restaurant groups",
    monthlyPrice: 3999,
    yearlyPrice: 39999,
    yearlyDiscountPercent: 17,
    offers: {
      monthly: {
        enabled: false,
        label: "",
        discountedPrice: 0,
        discountPercent: 0,
        durationMonths: 1,
      },
      yearly: {
        enabled: true,
        label: "Save on yearly billing",
        discountedPrice: 39999,
        discountPercent: 17,
        durationMonths: 12,
      },
    },
    maxRestaurants: 3,
    maxStaff: 35,
    extraRestaurantMonthlyPrice: 0,
    trialDays: 7,
    displayFeatures: [
      "Up to 3 Restaurants",
      "Up to 35 Staff",
      "POS / Orders / Billing",
      "Inventory Management",
      "Vendor Ordering",
      "Vendor Settlement",
      "Advanced Analytics",
      "Export Reports",
      "Priority Support",
    ],
    features: {
      inventoryManagement: true,
      vendorOrdering: true,
      vendorSettlement: true,
      reportsAnalytics: "advanced",
      exportEnabled: true,
      multiRestaurantDashboard: false,
      customSettlementCycles: true,
      auditLogs: false,
      prioritySupport: "priority",
      apiIntegrationReady: false,
    },
    isPopular: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    code: "SCALE_ADMIN",
    name: "Scale Admin",
    description: "Best for multi-outlet business",
    monthlyPrice: 7999,
    yearlyPrice: 79999,
    yearlyDiscountPercent: 17,
    offers: {
      monthly: {
        enabled: false,
        label: "",
        discountedPrice: 0,
        discountPercent: 0,
        durationMonths: 1,
      },
      yearly: {
        enabled: true,
        label: "Save on yearly billing",
        discountedPrice: 79999,
        discountPercent: 17,
        durationMonths: 12,
      },
    },
    maxRestaurants: 10,
    maxStaff: 9999,
    extraRestaurantMonthlyPrice: 999,
    trialDays: 7,
    displayFeatures: [
      "4 to 10 Restaurants",
      "Unlimited Staff",
      "POS / Orders / Billing",
      "Inventory Management",
      "Vendor Ordering",
      "Vendor Settlement",
      "Advanced + Vendor Analytics",
      "Export Reports",
      "Multi-Restaurant Dashboard",
      "Custom Settlement Cycles",
      "Audit Logs",
      "Fastest Support",
      "API / Integration Ready",
    ],
    features: {
      inventoryManagement: true,
      vendorOrdering: true,
      vendorSettlement: true,
      reportsAnalytics: "enterprise",
      exportEnabled: true,
      multiRestaurantDashboard: true,
      customSettlementCycles: true,
      auditLogs: true,
      prioritySupport: "fastest",
      apiIntegrationReady: true,
    },
    isPopular: false,
    isActive: true,
    sortOrder: 3,
  },
];
