export const DEFAULT_VENDOR_SUBSCRIPTION_PLANS = [
  {
    code: "BASIC_VENDOR",
    name: "Basic Plan",
    tagline: "Operate",
    description: "Operate your business with product, stock, and order basics.",
    tier: "basic",
    monthlyPrice: 199,
    priceDisplay: "₹0 - ₹199 / month",
    badgeLabel: "Core Access",
    restaurantLimit: 2,
    restaurantLimitLabel: "Up to 2 restaurants",
    featureSummary: [
      "Login & Access",
      "Vendor Profile",
      "Product Catalog",
      "Product Images Upload",
      "Add / Edit / Delete Products",
      "Receive Orders",
      "Update Order Status",
      "Basic Order List",
      "Invoice Preview",
      "Basic Dashboard",
    ],
    includedFeatures: [
      "My Products",
      "Inventory / Stock",
      "Vendor Management",
      "Order processing",
      "Invoice preview",
      "Restaurant connection up to 2",
      "Basic dashboard counts only",
    ],
    excludedFeatures: [
      "Settlement tracking",
      "Outstanding / borrow tracking",
      "Accounts module",
      "Analytics",
      "Reports & Excel export",
      "Statement download",
      "Payment cycle tools",
    ],
    lockedTriggers: [
      "Analytics click",
      "Reports click",
      "Settlement tracking",
      "Connect 3rd restaurant",
      "Download statement",
      "Advanced report export / filter",
    ],
    pageAccess: [
      "Dashboard: basic counts",
      "My Products: manage products",
      "Inventory / Stock: manage stock",
      "Vendor Management: orders and status update",
      "Accounts: locked",
      "Analytics: locked",
      "Reports: limited / no reports",
      "Settings: profile, bank, notification",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    code: "PRO_VENDOR",
    name: "Pro Plan",
    tagline: "Manage Money",
    description: "Track settlements, accounts, analytics, and stronger reports.",
    tier: "pro",
    monthlyPrice: 1299,
    priceDisplay: "₹799 - ₹1,299 / month",
    badgeLabel: "Finance Access",
    restaurantLimit: 20,
    restaurantLimitLabel: "Up to 15 - 20 restaurants",
    featureSummary: [
      "Everything in BASIC +",
      "Full order history",
      "Full invoice & bill download",
      "Settlement tracking",
      "Borrow / outstanding tracking",
      "Accounts module",
      "Analytics dashboard",
      "Sales / product / settlement reports",
      "Excel export",
      "Restaurant-wise sales view",
    ],
    includedFeatures: [
      "Accounts module access",
      "Settlement tracking",
      "Outstanding monitoring",
      "Analytics dashboard",
      "Reports with Excel export",
      "Statement download",
      "Payment cycle visibility",
    ],
    excludedFeatures: [
      "Unlimited restaurants",
      "Premium filters",
      "Branch / chain analytics",
      "Premium support",
      "Automation / API future access",
    ],
    lockedTriggers: [
      "Premium reports & filters",
      "Marketplace / lead access",
      "Custom settlement cycle",
      "Branch / chain analytics",
      "Automation features",
    ],
    pageAccess: [
      "Dashboard: revenue, outstanding, settlement summary",
      "My Products: all basic features",
      "Inventory / Stock: stock history & tools",
      "Vendor Management: settlements and outstanding",
      "Accounts: outstanding payment cycle",
      "Analytics: dashboard access",
      "Reports: standard reports + Excel export",
      "Settings: all basic features",
    ],
    isPopular: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    code: "BUSINESS_VENDOR",
    name: "Business Plan",
    tagline: "Grow & Optimize",
    description: "Scale with unlimited restaurants, advanced analytics, exports, and support.",
    tier: "business",
    monthlyPrice: 2499,
    priceDisplay: "₹2,499 / month",
    badgeLabel: "Growth Access",
    restaurantLimit: 9999,
    restaurantLimitLabel: "Unlimited restaurants",
    featureSummary: [
      "Everything in PRO +",
      "Unlimited restaurants",
      "Advanced analytics",
      "Advanced reports",
      "Premium reports & filters",
      "Excel & bulk export",
      "Account statement download",
      "Marketplace / lead access",
      "Priority support",
      "Custom settlement cycle",
    ],
    includedFeatures: [
      "Unlimited restaurant connection",
      "Advanced analytics and reports",
      "Premium reports and filters",
      "Bulk export and statements",
      "Lead / marketplace access",
      "Priority support",
      "Custom settlement cycle",
      "Future automation / API readiness",
    ],
    excludedFeatures: [],
    lockedTriggers: [],
    pageAccess: [
      "Dashboard: advanced KPIs and comparison",
      "My Products: all basic + advanced",
      "Inventory / Stock: demand planning and reports",
      "Vendor Management: settlement tools and downloads",
      "Accounts: advanced finance and statement download",
      "Analytics: advanced analytics & comparison",
      "Reports: advanced exports, custom filters, bulk export",
      "Settings: all features",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 3,
  },
];
