const ORDER_STATUS = {
  PLACED: "PLACED",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  READY: "READY",
  SERVED: "SERVED",
  BILLED: "BILLED",
  PAID: "PAID",
};

export default ORDER_STATUS;
